# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.active_period import ActivePeriod  # noqa: E501
from openapi_client.rest import ApiException

class TestActivePeriod(unittest.TestCase):
    """ActivePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ActivePeriod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.active_period.ActivePeriod()  # noqa: E501
        if include_optional :
            return ActivePeriod(
                start = '2017-08-14T14:54:01-04:00', 
                end = '2017-08-14T14:54:01-04:00'
            )
        else :
            return ActivePeriod(
        )

    def testActivePeriod(self):
        """Test ActivePeriod"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
