# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.live_facility import LiveFacility  # noqa: E501
from openapi_client.rest import ApiException

class TestLiveFacility(unittest.TestCase):
    """LiveFacility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LiveFacility
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.live_facility.LiveFacility()  # noqa: E501
        if include_optional :
            return LiveFacility(
                links = openapi_client.models.service_links.Service_links(
                    self = '0', ), 
                included = [
                    openapi_client.models.service_included.Service_included(
                        type = '0', 
                        id = '0', )
                    ], 
                data = openapi_client.models.live_facility_resource.LiveFacilityResource(
                    type = '0', 
                    relationships = openapi_client.models.relationships.relationships(), 
                    links = openapi_client.models.links.links(), 
                    id = '0', 
                    attributes = openapi_client.models.live_facility_resource_attributes.LiveFacilityResource_attributes(
                        updated_at = '2017-08-14T15:38:58-04:00', 
                        properties = [
                            {value=197 Ivory St, Braintree, MA 02184, name=address}
                            ], ), )
            )
        else :
            return LiveFacility(
                data = openapi_client.models.live_facility_resource.LiveFacilityResource(
                    type = '0', 
                    relationships = openapi_client.models.relationships.relationships(), 
                    links = openapi_client.models.links.links(), 
                    id = '0', 
                    attributes = openapi_client.models.live_facility_resource_attributes.LiveFacilityResource_attributes(
                        updated_at = '2017-08-14T15:38:58-04:00', 
                        properties = [
                            {value=197 Ivory St, Braintree, MA 02184, name=address}
                            ], ), ),
        )

    def testLiveFacility(self):
        """Test LiveFacility"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
