# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.informed_entity import InformedEntity  # noqa: E501
from openapi_client.rest import ApiException

class TestInformedEntity(unittest.TestCase):
    """InformedEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InformedEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.informed_entity.InformedEntity()  # noqa: E501
        if include_optional :
            return InformedEntity(
                trip = 'CR-Weekday-Spring-17-517', 
                stop = 'Auburndale', 
                route_type = 2, 
                route = 'CR_Worcester', 
                facility = '405', 
                direction_id = 56, 
                activities = [BOARD, EXIT]
            )
        else :
            return InformedEntity(
        )

    def testInformedEntity(self):
        """Test InformedEntity"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
