# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.shape_resource_relationships_stops_links import ShapeResourceRelationshipsStopsLinks  # noqa: E501
from openapi_client.rest import ApiException

class TestShapeResourceRelationshipsStopsLinks(unittest.TestCase):
    """ShapeResourceRelationshipsStopsLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ShapeResourceRelationshipsStopsLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.shape_resource_relationships_stops_links.ShapeResourceRelationshipsStopsLinks()  # noqa: E501
        if include_optional :
            return ShapeResourceRelationshipsStopsLinks(
                _self = '0', 
                related = '0'
            )
        else :
            return ShapeResourceRelationshipsStopsLinks(
        )

    def testShapeResourceRelationshipsStopsLinks(self):
        """Test ShapeResourceRelationshipsStopsLinks"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
