# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.route_resource_attributes import RouteResourceAttributes  # noqa: E501
from openapi_client.rest import ApiException

class TestRouteResourceAttributes(unittest.TestCase):
    """RouteResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RouteResourceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.route_resource_attributes.RouteResourceAttributes()  # noqa: E501
        if include_optional :
            return RouteResourceAttributes(
                type = 1, 
                text_color = '000000', 
                sort_order = 56, 
                short_name = 'Red', 
                long_name = 'Red Line', 
                fare_class = 'Free', 
                direction_names = [
                    '0'
                    ], 
                direction_destinations = [
                    '0'
                    ], 
                description = 'Rapid Transit', 
                color = 'FFFFFF'
            )
        else :
            return RouteResourceAttributes(
        )

    def testRouteResourceAttributes(self):
        """Test RouteResourceAttributes"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
