# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.vehicle_resource_attributes import VehicleResourceAttributes  # noqa: E501
from openapi_client.rest import ApiException

class TestVehicleResourceAttributes(unittest.TestCase):
    """VehicleResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VehicleResourceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.vehicle_resource_attributes.VehicleResourceAttributes()  # noqa: E501
        if include_optional :
            return VehicleResourceAttributes(
                updated_at = '2017-08-14T16:04:44-04:00', 
                speed = 16.0, 
                longitude = 42.32941818237305, 
                latitude = -71.27239990234375, 
                label = '1817', 
                direction_id = 56, 
                current_stop_sequence = 8, 
                current_status = 'IN_TRANSIT_TO', 
                bearing = 174
            )
        else :
            return VehicleResourceAttributes(
        )

    def testVehicleResourceAttributes(self):
        """Test VehicleResourceAttributes"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
