# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.too_many_requests import TooManyRequests  # noqa: E501
from openapi_client.rest import ApiException

class TestTooManyRequests(unittest.TestCase):
    """TooManyRequests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TooManyRequests
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.too_many_requests.TooManyRequests()  # noqa: E501
        if include_optional :
            return TooManyRequests(
                errors = [
                    openapi_client.models.too_many_requests_errors.TooManyRequests_errors(
                        status = '429', 
                        detail = 'You have exceeded your allowed usage rate.', 
                        code = 'rate_limited', )
                    ]
            )
        else :
            return TooManyRequests(
                errors = [
                    openapi_client.models.too_many_requests_errors.TooManyRequests_errors(
                        status = '429', 
                        detail = 'You have exceeded your allowed usage rate.', 
                        code = 'rate_limited', )
                    ],
        )

    def testTooManyRequests(self):
        """Test TooManyRequests"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
