# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.line import Line  # noqa: E501
from openapi_client.rest import ApiException

class TestLine(unittest.TestCase):
    """Line unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Line
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.line.Line()  # noqa: E501
        if include_optional :
            return Line(
                links = openapi_client.models.service_links.Service_links(
                    self = '0', ), 
                included = [
                    openapi_client.models.service_included.Service_included(
                        type = '0', 
                        id = '0', )
                    ], 
                data = openapi_client.models.line_resource.LineResource(
                    type = '0', 
                    relationships = openapi_client.models.relationships.relationships(), 
                    links = openapi_client.models.links.links(), 
                    id = '0', 
                    attributes = openapi_client.models.line_resource_attributes.LineResource_attributes(
                        text_color = '000000', 
                        sort_order = 56, 
                        short_name = 'CT2', 
                        long_name = 'Sullivan - Ruggles', 
                        color = 'FFFFFF', ), )
            )
        else :
            return Line(
                data = openapi_client.models.line_resource.LineResource(
                    type = '0', 
                    relationships = openapi_client.models.relationships.relationships(), 
                    links = openapi_client.models.links.links(), 
                    id = '0', 
                    attributes = openapi_client.models.line_resource_attributes.LineResource_attributes(
                        text_color = '000000', 
                        sort_order = 56, 
                        short_name = 'CT2', 
                        long_name = 'Sullivan - Ruggles', 
                        color = 'FFFFFF', ), ),
        )

    def testLine(self):
        """Test Line"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
