# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.vehicles import Vehicles  # noqa: E501
from openapi_client.rest import ApiException

class TestVehicles(unittest.TestCase):
    """Vehicles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Vehicles
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.vehicles.Vehicles()  # noqa: E501
        if include_optional :
            return Vehicles(
                links = openapi_client.models.schedules_links.Schedules_links(
                    self = '0', 
                    prev = '0', 
                    next = '0', 
                    last = '0', 
                    first = '0', ), 
                data = [
                    openapi_client.models.vehicle_resource.VehicleResource(
                        type = '0', 
                        relationships = openapi_client.models.vehicle_resource_relationships.VehicleResource_relationships(
                            trip = openapi_client.models.prediction_resource_relationships_trip.PredictionResource_relationships_trip(
                                links = openapi_client.models.prediction_resource_relationships_trip_links.PredictionResource_relationships_trip_links(
                                    self = '0', 
                                    related = '0', ), 
                                data = openapi_client.models.prediction_resource_relationships_trip_data.PredictionResource_relationships_trip_data(
                                    type = '0', 
                                    id = '0', ), ), 
                            stop = openapi_client.models.prediction_resource_relationships_stop.PredictionResource_relationships_stop(), 
                            route = openapi_client.models.prediction_resource_relationships_route.PredictionResource_relationships_route(), ), 
                        links = openapi_client.models.links.links(), 
                        id = '0', 
                        attributes = openapi_client.models.vehicle_resource_attributes.VehicleResource_attributes(
                            updated_at = '2017-08-14T16:04:44-04:00', 
                            speed = 16.0, 
                            longitude = 42.32941818237305, 
                            latitude = -71.27239990234375, 
                            label = '1817', 
                            direction_id = 56, 
                            current_stop_sequence = 8, 
                            current_status = 'IN_TRANSIT_TO', 
                            bearing = 174, ), )
                    ]
            )
        else :
            return Vehicles(
                data = [
                    openapi_client.models.vehicle_resource.VehicleResource(
                        type = '0', 
                        relationships = openapi_client.models.vehicle_resource_relationships.VehicleResource_relationships(
                            trip = openapi_client.models.prediction_resource_relationships_trip.PredictionResource_relationships_trip(
                                links = openapi_client.models.prediction_resource_relationships_trip_links.PredictionResource_relationships_trip_links(
                                    self = '0', 
                                    related = '0', ), 
                                data = openapi_client.models.prediction_resource_relationships_trip_data.PredictionResource_relationships_trip_data(
                                    type = '0', 
                                    id = '0', ), ), 
                            stop = openapi_client.models.prediction_resource_relationships_stop.PredictionResource_relationships_stop(), 
                            route = openapi_client.models.prediction_resource_relationships_route.PredictionResource_relationships_route(), ), 
                        links = openapi_client.models.links.links(), 
                        id = '0', 
                        attributes = openapi_client.models.vehicle_resource_attributes.VehicleResource_attributes(
                            updated_at = '2017-08-14T16:04:44-04:00', 
                            speed = 16.0, 
                            longitude = 42.32941818237305, 
                            latitude = -71.27239990234375, 
                            label = '1817', 
                            direction_id = 56, 
                            current_stop_sequence = 8, 
                            current_status = 'IN_TRANSIT_TO', 
                            bearing = 174, ), )
                    ],
        )

    def testVehicles(self):
        """Test Vehicles"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
