# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.alert_resource_attributes import AlertResourceAttributes  # noqa: E501
from openapi_client.rest import ApiException

class TestAlertResourceAttributes(unittest.TestCase):
    """AlertResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AlertResourceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.alert_resource_attributes.AlertResourceAttributes()  # noqa: E501
        if include_optional :
            return AlertResourceAttributes(
                url = 'http://www.mbta.com/uploadedfiles/Documents/Schedules_and_Maps/Commuter_Rail/fairmount.pdf?led=6/3/2017%201:22:09%20AM', 
                updated_at = '2017-08-14T14:54:01-04:00', 
                timeframe = 'Ongoing', 
                short_header = 'All weekend Fairmount Line trains will be bused between Morton St. & Readville due to construction of Blue Hill Ave Station.
', 
                severity = 10, 
                service_effect = 'Minor Route 216 delay', 
                lifecycle = 'Ongoing', 
                informed_entity = [
                    openapi_client.models.informed_entity.InformedEntity(
                        trip = 'CR-Weekday-Spring-17-517', 
                        stop = 'Auburndale', 
                        route_type = 2, 
                        route = 'CR_Worcester', 
                        facility = '405', 
                        direction_id = 56, 
                        activities = [BOARD, EXIT], )
                    ], 
                header = 'Starting 6/3, all weekend Fairmount Line trains will be bused between Morton St. and Readville in both directions due to construction of the new Blue Hill Avenue Station.
', 
                effect_name = 'Delay', 
                effect = 'ACCESS_ISSUE', 
                description = 'If entering the station, cross Tremont Street to the Boston Common and use Park Street Elevator 978 to the Green Line westbound platform. Red Line platform access is available via the elevator beyond the fare gates. If exiting the station, please travel down the Winter Street Concourse toward Downtown Crossing Station, exit through the fare gates, and take Downtown Crossing Elevator 892 to the street level.
', 
                created_at = '2017-08-14T14:54:01-04:00', 
                cause = 'ACCIDENT', 
                banner = 'All service suspended due to severe weather', 
                active_period = [
                    openapi_client.models.active_period.ActivePeriod(
                        start = '2017-08-14T14:54:01-04:00', 
                        end = '2017-08-14T14:54:01-04:00', )
                    ]
            )
        else :
            return AlertResourceAttributes(
        )

    def testAlertResourceAttributes(self):
        """Test AlertResourceAttributes"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
