# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class LiveFacilityResourceAttributes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'updated_at': 'datetime',
        'properties': 'list[FacilityProperty]'
    }

    attribute_map = {
        'updated_at': 'updated_at',
        'properties': 'properties'
    }

    def __init__(self, updated_at=None, properties=None, local_vars_configuration=None):  # noqa: E501
        """LiveFacilityResourceAttributes - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._updated_at = None
        self._properties = None
        self.discriminator = None

        if updated_at is not None:
            self.updated_at = updated_at
        if properties is not None:
            self.properties = properties

    @property
    def updated_at(self):
        """Gets the updated_at of this LiveFacilityResourceAttributes.  # noqa: E501

        Time of last update  # noqa: E501

        :return: The updated_at of this LiveFacilityResourceAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this LiveFacilityResourceAttributes.

        Time of last update  # noqa: E501

        :param updated_at: The updated_at of this LiveFacilityResourceAttributes.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def properties(self):
        """Gets the properties of this LiveFacilityResourceAttributes.  # noqa: E501

        A list of name/value pairs that apply to the facility. See [MBTA's facility documentation](https://www.mbta.com/developers/gtfs/f#facilities_properties_definitions) for more information on the possible names and values.  # noqa: E501

        :return: The properties of this LiveFacilityResourceAttributes.  # noqa: E501
        :rtype: list[FacilityProperty]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this LiveFacilityResourceAttributes.

        A list of name/value pairs that apply to the facility. See [MBTA's facility documentation](https://www.mbta.com/developers/gtfs/f#facilities_properties_definitions) for more information on the possible names and values.  # noqa: E501

        :param properties: The properties of this LiveFacilityResourceAttributes.  # noqa: E501
        :type: list[FacilityProperty]
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LiveFacilityResourceAttributes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LiveFacilityResourceAttributes):
            return True

        return self.to_dict() != other.to_dict()
