# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class RoutePatternResourceRelationships(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'route': 'PredictionResourceRelationshipsRoute',
        'representative_trip': 'RoutePatternResourceRelationshipsRepresentativeTrip'
    }

    attribute_map = {
        'route': 'route',
        'representative_trip': 'representative_trip'
    }

    def __init__(self, route=None, representative_trip=None, local_vars_configuration=None):  # noqa: E501
        """RoutePatternResourceRelationships - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._route = None
        self._representative_trip = None
        self.discriminator = None

        if route is not None:
            self.route = route
        if representative_trip is not None:
            self.representative_trip = representative_trip

    @property
    def route(self):
        """Gets the route of this RoutePatternResourceRelationships.  # noqa: E501


        :return: The route of this RoutePatternResourceRelationships.  # noqa: E501
        :rtype: PredictionResourceRelationshipsRoute
        """
        return self._route

    @route.setter
    def route(self, route):
        """Sets the route of this RoutePatternResourceRelationships.


        :param route: The route of this RoutePatternResourceRelationships.  # noqa: E501
        :type: PredictionResourceRelationshipsRoute
        """

        self._route = route

    @property
    def representative_trip(self):
        """Gets the representative_trip of this RoutePatternResourceRelationships.  # noqa: E501


        :return: The representative_trip of this RoutePatternResourceRelationships.  # noqa: E501
        :rtype: RoutePatternResourceRelationshipsRepresentativeTrip
        """
        return self._representative_trip

    @representative_trip.setter
    def representative_trip(self, representative_trip):
        """Sets the representative_trip of this RoutePatternResourceRelationships.


        :param representative_trip: The representative_trip of this RoutePatternResourceRelationships.  # noqa: E501
        :type: RoutePatternResourceRelationshipsRepresentativeTrip
        """

        self._representative_trip = representative_trip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoutePatternResourceRelationships):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RoutePatternResourceRelationships):
            return True

        return self.to_dict() != other.to_dict()
