# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: developer@mbta.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class SchedulesLinks(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        '_self': 'str',
        'prev': 'str',
        'next': 'str',
        'last': 'str',
        'first': 'str'
    }

    attribute_map = {
        '_self': 'self',
        'prev': 'prev',
        'next': 'next',
        'last': 'last',
        'first': 'first'
    }

    def __init__(self, _self=None, prev=None, next=None, last=None, first=None, local_vars_configuration=None):  # noqa: E501
        """SchedulesLinks - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self.__self = None
        self._prev = None
        self._next = None
        self._last = None
        self._first = None
        self.discriminator = None

        if _self is not None:
            self._self = _self
        if prev is not None:
            self.prev = prev
        if next is not None:
            self.next = next
        if last is not None:
            self.last = last
        if first is not None:
            self.first = first

    @property
    def _self(self):
        """Gets the _self of this SchedulesLinks.  # noqa: E501

        Link to this page of results  # noqa: E501

        :return: The _self of this SchedulesLinks.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this SchedulesLinks.

        Link to this page of results  # noqa: E501

        :param _self: The _self of this SchedulesLinks.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def prev(self):
        """Gets the prev of this SchedulesLinks.  # noqa: E501

        Link to the previous page of results  # noqa: E501

        :return: The prev of this SchedulesLinks.  # noqa: E501
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this SchedulesLinks.

        Link to the previous page of results  # noqa: E501

        :param prev: The prev of this SchedulesLinks.  # noqa: E501
        :type: str
        """

        self._prev = prev

    @property
    def next(self):
        """Gets the next of this SchedulesLinks.  # noqa: E501

        Link to the next page of results  # noqa: E501

        :return: The next of this SchedulesLinks.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this SchedulesLinks.

        Link to the next page of results  # noqa: E501

        :param next: The next of this SchedulesLinks.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def last(self):
        """Gets the last of this SchedulesLinks.  # noqa: E501

        Link to the last page of results  # noqa: E501

        :return: The last of this SchedulesLinks.  # noqa: E501
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this SchedulesLinks.

        Link to the last page of results  # noqa: E501

        :param last: The last of this SchedulesLinks.  # noqa: E501
        :type: str
        """

        self._last = last

    @property
    def first(self):
        """Gets the first of this SchedulesLinks.  # noqa: E501

        Link to the first page of results  # noqa: E501

        :return: The first of this SchedulesLinks.  # noqa: E501
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this SchedulesLinks.

        Link to the first page of results  # noqa: E501

        :param first: The first of this SchedulesLinks.  # noqa: E501
        :type: str
        """

        self._first = first

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SchedulesLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SchedulesLinks):
            return True

        return self.to_dict() != other.to_dict()
